import { HabitWithLockStatus } from "@/types";

/**
 * Generates a username based on an email address.
 *
 * The username is generated by taking the local part of the email address
 * (i.e. the part before the '@' symbol), converting it to lowercase, and
 * removing any non-alphanumeric characters. A random four-digit number is then
 * appended to the end of the username.
 *
 * @param {string} email - The email address to generate a username from.
 * @returns {string} The generated username.
 */
export function generateUsername(email: string): string {
  const base = email
    .split("@")[0]
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "");
  const suffix = Math.floor(Math.random() * 10000);
  return `${base}${suffix}`;
}

/* Transform data to include id and locked status */
export const transformHabitsToLockStatus = (
  habits: string[],
): HabitWithLockStatus[] => {
  return habits.map((habit) => ({
    text: habit,
    id: crypto.randomUUID(),
    locked: false,
  }));
};
export function formatShortDate(iso: string | Date): string {
  const date = typeof iso === "string" ? new Date(iso) : iso;

  return date.toLocaleDateString("en-US", {
    month: "short", // "Aug"
    day: "numeric", // "26"
  });
}
export function toUtcMidnight(input: string | Date): Date {
  const d = typeof input === "string" ? new Date(input) : input;
  return new Date(
    Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate(), 0, 0, 0, 0),
  );
}

// lib/helpers.ts

export function calculateHabitStats(
  logs: { date: Date; completed: boolean }[],
) {
  const completedLogs = logs.filter((log) => log.completed);

  // Set of timestamps (in UTC ms) for fast day-by-day lookup
  const completedDays = new Set(
    completedLogs.map((l) => toUtcMidnight(l.date).getTime()),
  );

  const today = toUtcMidnight(new Date());
  const oneDayMs = 24 * 60 * 60 * 1000;

  const completedToday = completedDays.has(today.getTime());

  // Determine where to start counting the streak:
  // If completed today, start checking backwards from today.
  // If not completed today, start checking backwards from yesterday (the streak isn't broken yet today!).
  let currentCheck = completedToday
    ? today.getTime()
    : today.getTime() - oneDayMs;
  let streak = 0;

  while (completedDays.has(currentCheck)) {
    streak++;
    currentCheck -= oneDayMs; // step back 1 day
  }

  return { completedToday, streak };
}
