import { HabitWithLockStatus } from "@/types";

/**
 * Generates a username based on an email address.
 *
 * The username is generated by taking the local part of the email address
 * (i.e. the part before the '@' symbol), converting it to lowercase, and
 * removing any non-alphanumeric characters. A random four-digit number is then
 * appended to the end of the username.
 *
 * @param {string} email - The email address to generate a username from.
 * @returns {string} The generated username.
 */
function generateUsername(email: string): string {
  const base = email
    .split("@")[0]
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "");
  const suffix = Math.floor(Math.random() * 10000);
  return `${base}${suffix}`;
}

/* Transform data to include id and locked status */
export const transformHabitsToLockStatus = (
  habits: string[],
): HabitWithLockStatus[] => {
  return habits.map((habit) => ({
    text: habit,
    id: crypto.randomUUID(),
    locked: false,
  }));
};
function formatShortDate(iso: string | Date): string {
  const date = typeof iso === "string" ? new Date(iso) : iso;

  return date.toLocaleDateString("en-US", {
    month: "short", // "Aug"
    day: "numeric", // "26"
  });
}
export { generateUsername, formatShortDate };
